# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cloudhealth-collector
description: A Helm chart for CloudHealth's Kubernetes Collector and Optimizer Agent
type: application
version: 5.0.4-alpha
appVersion: "4.1.0"
dependencies:
  - name: cloudhealth-optimization-controller
    repository: file://subcharts/k8s-optimization-0.2.0.tgz
    version: 0.2.0
    condition: chOptimizer.enabled
home: https://cloudhealth.vmware.com/
sources:
- https://github.com/CloudHealth/helm
maintainers:
  - name: CloudHealth Team
    email: cht-core-containers@groups.vmware.com
