# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cloudhealth-collector
description: A Helm chart for CloudHealth's Kubernetes Collector Agent
type: application
category: Cost
version: 4.1.0
icon: https://d1fto35gcfffzn.cloudfront.net/images/Tanzu-Logomark.svg
appVersion: "5.0.0"
home: https://cloudhealth.vmware.com/
sources:
- https://github.com/CloudHealth/helm
maintainers:
  - name: CloudHealth Team
    email: cht-core-containers@groups.vmware.com
