# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cloudhealth-collector
description: A Helm chart for CloudHealth's Kubernetes Collector and Optimizer Agent
type: application
version: 5.7.0-beta
appVersion: "5.2.0"
dependencies:
  - name: k8s-optimization
    repository: oci://projects.registry.vmware.com/kubernetes-optimization
    version: 1.0.0
    condition: optimizer.enabled
home: https://cloudhealth.vmware.com/
icon: https://d1fto35gcfffzn.cloudfront.net/images/Tanzu-Logomark.svg
sources:
- https://github.com/CloudHealth/helm
maintainers:
  - name: CloudHealth Team
    email: cht-core-containers.pdl@broadcom.com
annotations:
  category: Cost
