# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cloudhealth-collector
description: A Helm chart for CloudHealth's Kubernetes Collector and Optimizer Agent
type: application
version: 5.1.0-alpha
appVersion: "4.1.0"
dependencies:
  - name: k8s-optimization
    repository: oci://projects.registry.vmware.com/kubernetes-optimization-controller
    version: 1.0.0-beta
    condition: optimizer.enabled
home: https://cloudhealth.vmware.com/
sources:
- https://github.com/CloudHealth/helm
maintainers:
  - name: CloudHealth Team
    email: cht-core-containers@groups.vmware.com
