# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cloudhealth-collector
description: A Helm chart for CloudHealth's Kubernetes Collector Agent
type: application
version: 4.6.1
appVersion: "7.0.0"
home: https://cloudhealth.vmware.com/
icon: https://d1fto35gcfffzn.cloudfront.net/images/Tanzu-Logomark.svg
sources:
- https://github.com/CloudHealth/helm
maintainers:
  - name: CloudHealth Team
    email: cht-core-containers.pdl@broadcom.com
annotations:
  category: Cost
