{{- /*
Copyright 2023 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.chOptimizer.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cloudhealth-optimizer-agent.name" . }}
  labels:
    {{- include "cloudhealth-collector.labels" . | nindent 4 }}
  {{- with .Values.deployAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "cloudhealth-collector.serviceAccountName" . }}
          containers:
          - name: hello
            env:
              - name: CHAPI_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ include "cloudhealth-collector.secretName" . }}
                    key: chapiToken
              - name: CHT_CLUSTER_NAME
                value: {{.Values.clusterName | required "A valid clusterName required!" | quote }}
              - name: CHT_REGION
                value: {{.Values.chtRegion | default "us-east-1" }}
            image: "{{ .Values.chOptimizer.image.repository }}:{{ .Values.chOptimizer.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.chOptimizer.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          restartPolicy: OnFailure
{{- end }}